# Generated by Django 5.1.1 on 2024-10-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro',
            new_name='Produtos',
        ),
    ]
